/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 city.glb --transform 
Files: city.glb [692.85MB] > C:\Users\iona8\Desktop\city-transformed.glb [20.68MB] (97%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function City(props) {
    const { nodes, materials } = useGLTF("/city-transformed.glb");
    return (
        <group {...props} dispose={null}>
            <group
                position={[-1.442, 0.724, -1.041]}
                rotation={[-Math.PI, -1.571, 0]}
                scale={-0.422}
            >
                <mesh
                    geometry={nodes.MainBuilding_Low039.geometry}
                    material={materials["MainBuilding.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_1.geometry}
                    material={materials["Door.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_2.geometry}
                    material={materials["ATM.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_3.geometry}
                    material={materials["ATMGlass.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_4.geometry}
                    material={materials["Pipes.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_5.geometry}
                    material={materials["Sign.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_6.geometry}
                    material={materials.PaletteMaterial001}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_7.geometry}
                    material={materials["Concrete.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_8.geometry}
                    material={materials.PaletteMaterial002}
                />
            </group>
            <mesh
                geometry={nodes.Z_CY_B_001_05.geometry}
                material={materials.Scifi_Wall_Black_01}
                position={[-0.18, 2.725, -10.841]}
                rotation={[0, -0.501, 0]}
                scale={4.013}
            />
            <mesh
                geometry={nodes.Z_CY_B_01_036.geometry}
                material={materials.GalvanizedSteel1}
                position={[-0.948, 1.256, -10.335]}
                rotation={[-Math.PI, 0.474, -Math.PI]}
                scale={8.447}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_002_07_Wall_PaintedRough_Blue_01.geometry
                }
                material={materials.Wall_PaintedRough_Blue_01}
                position={[-1.306, 2.49, -3.163]}
                scale={3.218}
            />
            <mesh
                geometry={nodes.Z_CY_B_002_07_Z_BannerB_Atlas_mtl.geometry}
                material={materials.Z_BannerB_Atlas_mtl}
                position={[-1.276, 2.489, -3.163]}
                scale={3.218}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_MetalPaintedDBrown_VRayMtl.geometry
                }
                material={materials.MetalPaintedDBrown_VRayMtl}
                position={[-1.378, 4.198, -1.86]}
                scale={6.585}
            />
            <mesh
                geometry={nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl.geometry}
                material={materials["Z_BannerA_Atlas_mtl.003"]}
                position={[-1.166, 4.206, -1.86]}
                scale={6.585}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl001.geometry
                }
                material={materials["Z_BannerA_Atlas_mtl.004"]}
                position={[-1.166, 4.206, -1.86]}
                scale={6.585}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl003.geometry
                }
                material={materials["Z_BannerA_Atlas_mtl.006"]}
                position={[-1.166, 4.206, -1.86]}
                scale={6.585}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl005.geometry
                }
                material={materials["Z_BannerA_Atlas_mtl.002"]}
                position={[-1.166, 4.206, -1.86]}
                scale={6.585}
            />
            <mesh
                geometry={nodes.Z_CY_B_005_01.geometry}
                material={materials["Wall_PaintedRough_Metal_01b.002"]}
                position={[-1.396, 4.185, -2.903]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={3.5}
            />
            <mesh
                geometry={nodes.Z_CY_B_05_019.geometry}
                material={materials.Wall_PaintedRough_Metal_01}
                position={[-1.309, 4.148, -3.366]}
                scale={6.143}
            />
            <mesh
                geometry={nodes.Z_CY_B_06_015.geometry}
                material={materials["Metal_panels_01_Mat.001"]}
                position={[-0.881, 1.153, -3.585]}
                scale={3.956}
            />
            <mesh
                geometry={nodes.Z_CY_B_06_016.geometry}
                material={materials["Floor_v3_mtl.001"]}
                position={[-0.797, 1.545, -4.327]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={3.956}
            />
            <mesh
                geometry={nodes.Z_CY_B_06_017.geometry}
                material={materials.WireTrim_mtl}
                position={[-0.004, 3.648, -2.794]}
                rotation={[0, -1.075, 0]}
                scale={5.29}
            />
            <mesh
                geometry={nodes.Z_CY_B_07_031.geometry}
                material={materials["GalvanizedSteelDirt_VRayMtl.001"]}
                position={[-1.456, 4.731, -9.794]}
                rotation={[Math.PI, -0.969, Math.PI]}
                scale={3.935}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_07_055_MetalPaintedWhite_VRayMtl.geometry
                }
                material={materials["MetalPaintedWhite_VRayMtl.001"]}
                position={[-1.419, 6.734, -9.791]}
                rotation={[Math.PI, -0.969, Math.PI]}
                scale={3.935}
            />
            <mesh
                geometry={nodes.Z_CY_B_07_055_Z_BannerB_Atlas_mtl.geometry}
                material={materials["Z_BannerB_Atlas_mtl.001"]}
                position={[-1.42, 6.737, -9.79]}
                rotation={[Math.PI, -0.969, Math.PI]}
                scale={3.935}
            />
            <mesh
                geometry={nodes.Z_CY_B_07_063.geometry}
                material={materials.AtlasHoloB_mtl}
                position={[0.563, 7.906, -12.729]}
                rotation={[-Math.PI, 0.959, -Math.PI]}
                scale={6.084}
            />
            <mesh
                geometry={nodes.Z_CY_B_09_012_Metal_distressed_iron.geometry}
                material={materials["Metal_distressed_iron.001"]}
                position={[-0.346, 1.77, -3.985]}
                scale={3.326}
            />
            <mesh
                geometry={nodes.Z_CY_B_09_016.geometry}
                material={materials.Scifi_Panels_L}
                position={[-1.438, 4.31, -0.222]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={4.091}
            />
            <mesh
                geometry={nodes.Z_CY_B_11_045_Z_BannerA_Atlas_mtl.geometry}
                material={materials["Z_BannerA_Atlas_mtl.001"]}
                position={[-1.397, 6.959, -5.721]}
                rotation={[0, -1.571, 0]}
                scale={7.696}
            />
            <mesh
                geometry={nodes.MachineryHeavy0109_L001.geometry}
                material={materials.MachineryHeavy0109_L}
                position={[0.506, 4.456, -3.303]}
                scale={0.119}
            />
            <group
                position={[-0.788, 4.305, -3.038]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={0.127}
            >
                <mesh
                    geometry={
                        nodes["d2a087e4-b204-4b70-9591-4b09f7f265b9016"]
                            .geometry
                    }
                    material={materials["d2a087e4-b204-4b70-9591-4b09f7f265b9"]}
                />
                <mesh
                    geometry={
                        nodes["d2a087e4-b204-4b70-9591-4b09f7f265b9016_1"]
                            .geometry
                    }
                    material={materials["CONCRETE.002"]}
                />
            </group>
            <group
                position={[0.942, 4.946, -3.414]}
                rotation={[0, 0.129, 0]}
                scale={[0.012, 0.008, 0.012]}
            >
                <mesh
                    geometry={nodes.Cylinder021.geometry}
                    material={materials.PaletteMaterial003}
                />
                <mesh
                    geometry={nodes.Cylinder021_1.geometry}
                    material={materials.PaletteMaterial004}
                />
            </group>
            <mesh
                geometry={nodes.Cylinder022.geometry}
                material={materials.PaletteMaterial005}
                position={[-0.871, 4.633, -2.677]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[0.014, 0.462, 0.014]}
            />
            <mesh
                geometry={nodes.Cube008.geometry}
                material={materials.PaletteMaterial006}
                position={[-1.441, 1.049, -7.221]}
                rotation={[Math.PI, -0.001, Math.PI]}
            />
            <mesh
                geometry={
                    nodes.Aset_street_props_S_ve2hddjga_02_LOD2004.geometry
                }
                material={materials.trashbag}
                position={[-0.803, 0.015, -3.242]}
                rotation={[1.5, 0.018, 2.856]}
                scale={0.006}
            />
            <mesh
                geometry={nodes.Aset_plastic__S_tlzkdilva_04_LOD2.geometry}
                material={materials["oil bottle"]}
                position={[-0.58, 0.031, -3.235]}
                rotation={[-Math.PI, -0.234, 0]}
                scale={0.004}
            />
            <mesh
                geometry={nodes.Aset_misc__M_ucynedrfa_LOD2.geometry}
                material={materials["/mat/Game_Master_unaligned_default"]}
                position={[-1.035, 0.021, -3.185]}
                rotation={[Math.PI / 2, 0, -0.039]}
                scale={0.009}
            />
            <mesh
                geometry={nodes.Aset_misc__M_ucmndaefa_LOD2.geometry}
                material={materials["Material.009"]}
                position={[-1.24, 0.021, -2.899]}
                rotation={[Math.PI / 2, 0, -0.868]}
                scale={0.009}
            />
            <mesh
                geometry={
                    nodes.Aset_industrial_hardware_S_vidrear_LOD2001.geometry
                }
                material={materials.Game_Master_Game_Master_Game_Master_default}
                position={[-1.401, 2.231, 0.089]}
                rotation={[Math.PI / 2, 0.513, 0]}
                scale={0.008}
            />
            <mesh
                geometry={nodes.Cube011.geometry}
                material={materials["Material.013"]}
                position={[-0.203, 4.881, -11.512]}
                rotation={[0, 1.086, 0]}
                scale={0.15}
            />
            <mesh
                geometry={nodes.Cube047.geometry}
                material={materials["Material.020"]}
                position={[1.293, 0.259, -0.727]}
                rotation={[-0.524, -1.363, -1.459]}
                scale={0.157}
            />
            <mesh
                geometry={nodes["1(5)png032"].geometry}
                material={materials["1(6).png"]}
                position={[1.319, 0.209, -3.15]}
                rotation={[1.736, 0.23, -2.201]}
                scale={0.845}
            />
            <mesh
                geometry={nodes.Cube166.geometry}
                material={materials.MT_Metall}
                position={[1.487, 6.898, -8.995]}
                scale={6.741}
            />
            <mesh
                geometry={nodes.Cube099.geometry}
                material={materials["MT_Metall Yellow"]}
                position={[-1.145, 0.326, 1.71]}
                rotation={[0, 0.01, Math.PI / 2]}
                scale={[0.109, 0.851, 0.851]}
            />
            <mesh
                geometry={nodes.Cube014.geometry}
                material={materials.PaletteMaterial007}
                position={[-0.935, 5.799, -10.516]}
                rotation={[-Math.PI, 0.487, -Math.PI]}
            />
            <group
                position={[-1.489, 2.9, 0.5]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.007, 0.359, 0.028]}
            >
                <mesh
                    geometry={nodes.Plane112.geometry}
                    material={materials.dekker}
                />
                <mesh
                    geometry={nodes.Plane112_1.geometry}
                    material={materials.dri}
                />
                <mesh
                    geometry={nodes.Plane112_2.geometry}
                    material={materials.forb}
                />
                <mesh
                    geometry={nodes.Plane112_3.geometry}
                    material={materials.hack}
                />
                <mesh
                    geometry={nodes.Plane112_4.geometry}
                    material={materials.tec}
                />
            </group>
            <mesh
                geometry={nodes.Pattern2D_6491.geometry}
                material={materials.PaletteMaterial008}
                position={[-1.089, 1.49, -1.501]}
                rotation={[Math.PI / 2, 0.056, -Math.PI / 2]}
                scale={0.001}
            />
            <group
                position={[1.442, 3.103, 1.808]}
                rotation={[-Math.PI / 2, 0, 1.93]}
                scale={[0.599, 0.401, 0.593]}
            >
                <mesh
                    geometry={nodes.Mesh014.geometry}
                    material={materials.PaletteMaterial009}
                />
                <mesh
                    geometry={nodes.Mesh014_1.geometry}
                    material={materials["M.001"]}
                />
            </group>
            <mesh
                geometry={nodes.MH_Metal_Pipes_008.geometry}
                material={materials["Material.041"]}
                position={[0.541, 3.895, -2.814]}
                rotation={[-Math.PI, Math.PI / 2, 0]}
                scale={0.227}
            />
            <mesh
                geometry={nodes.MH_Metal_Pipes_009.geometry}
                material={materials["Material.040"]}
                position={[0.946, 3.9, -3.787]}
                rotation={[-Math.PI, Math.PI / 2, 0]}
                scale={0.227}
            />
            <mesh
                geometry={nodes.Plane.geometry}
                material={materials.PaletteMaterial010}
                position={[4.459, 0.03, -2.46]}
                scale={[52, 52, 30.125]}
            />
            <mesh
                geometry={nodes.Plane001.geometry}
                material={materials.PaletteMaterial011}
                position={[0.022, 4.161, -3.042]}
                scale={[1.949, 1, 0.865]}
            />
            <group
                position={[1.062, 0.424, -1.865]}
                rotation={[-Math.PI, 0, 2.888]}
                scale={0.029}
            >
                <mesh
                    geometry={nodes.Plane013_1.geometry}
                    material={materials["Material.106"]}
                />
                <mesh
                    geometry={nodes.Plane013_2.geometry}
                    material={materials["Material.001_SMR"]}
                />
                <mesh
                    geometry={nodes.Plane013_3.geometry}
                    material={materials["Material.107"]}
                />
            </group>
            <mesh
                geometry={nodes.Plane022.geometry}
                material={materials["Material.018"]}
                position={[-0.972, 0.66, -3.188]}
                rotation={[1.739, -0.089, -0.735]}
                scale={0.203}
            />
            <group
                position={[-1.264, 0.488, 0.083]}
                rotation={[0, 1.571, 0]}
                scale={0.407}
            >
                <mesh
                    geometry={nodes.KB3D_CBP_VendingMachine_D_Main001.geometry}
                    material={materials.KB3D_CBP_AtlasDGBannerA}
                />
                <mesh
                    geometry={
                        nodes.KB3D_CBP_VendingMachine_D_Main001_1.geometry
                    }
                    material={materials.KB3D_CBP_SteelPanelShiny}
                />
                <mesh
                    geometry={
                        nodes.KB3D_CBP_VendingMachine_D_Main001_2.geometry
                    }
                    material={materials.KB3D_CBP_SteelPanelBright}
                />
            </group>
            <instancedMesh
                args={[nodes.Cube001.geometry, materials.PaletteMaterial002, 5]}
                instanceMatrix={nodes.Cube001.instanceMatrix}
            />
            <instancedMesh
                args={[
                    nodes.Cube001_1.geometry,
                    materials.PaletteMaterial002,
                    5,
                ]}
                instanceMatrix={nodes.Cube001_1.instanceMatrix}
            />
        </group>
    );
}

useGLTF.preload("/city-transformed.glb");
