/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cyberCity.glb --transform 
Files: cyberCity.glb [548.81MB] > C:\Users\iona8\Desktop\cyberCity-transformed.glb [14.75MB] (97%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CyberCity(props) {
    const { nodes, materials } = useGLTF("/models/cyberCity-transformed.glb");
    return (
        <group {...props} dispose={null}>
            <group
                position={[-4.521, 1.97, 0.716]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={-1.032}
            >
                <mesh
                    geometry={nodes.MainBuilding_Low039.geometry}
                    material={materials["MainBuilding.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_1.geometry}
                    material={materials["Door.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_2.geometry}
                    material={materials["ATM.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_3.geometry}
                    material={materials["ATMGlass.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_4.geometry}
                    material={materials["Pipes.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_5.geometry}
                    material={materials["Sign.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_6.geometry}
                    material={materials["Concrete.001"]}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_7.geometry}
                    material={materials.PaletteMaterial001}
                />
                <mesh
                    geometry={nodes.MainBuilding_Low039_8.geometry}
                    material={materials.PaletteMaterial002}
                />
            </group>
            <mesh
                geometry={nodes.Z_CY_B_002_07_Z_BannerB_Atlas_mtl.geometry}
                material={materials.Z_BannerB_Atlas_mtl}
                position={[8.999, 4.573, -9.147]}
                rotation={[0, -1.475, 0]}
                scale={7.644}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_MetalPaintedDBrown_VRayMtl.geometry
                }
                material={materials.MetalPaintedDBrown_VRayMtl}
                position={[2.923, 9.874, 17.73]}
                rotation={[0, 1.506, 0]}
                scale={20.874}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_Wall_PaintedRough_Blue_01.geometry
                }
                material={materials["Wall_PaintedRough_Blue_01.001"]}
                position={[2.961, 9.899, 17.164]}
                rotation={[0, 1.506, 0]}
                scale={20.874}
            />
            <mesh
                geometry={nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl.geometry}
                material={materials["Z_BannerA_Atlas_mtl.003"]}
                position={[2.967, 9.9, 17.06]}
                rotation={[0, 1.506, 0]}
                scale={20.874}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl001.geometry
                }
                material={materials["Z_BannerA_Atlas_mtl.004"]}
                position={[2.967, 9.9, 17.06]}
                rotation={[0, 1.506, 0]}
                scale={20.874}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_04_035_04_Z_BannerA_Atlas_mtl005.geometry
                }
                material={materials["Z_BannerA_Atlas_mtl.002"]}
                position={[2.967, 9.9, 17.06]}
                rotation={[0, 1.506, 0]}
                scale={20.874}
            />
            <mesh
                geometry={nodes.Z_CY_B_05_019003.geometry}
                material={materials.Wall_PaintedRough_Metal_01}
                position={[4.926, 12.365, -26.051]}
                rotation={[0, 1.52, 0]}
                scale={18.296}
            />
            <mesh
                geometry={nodes.Z_CY_B_07_031.geometry}
                material={materials["GalvanizedSteelDirt_VRayMtl.001"]}
                position={[9.047, 4.731, 0.055]}
                rotation={[Math.PI, -0.969, Math.PI]}
                scale={3.935}
            />
            <mesh
                geometry={
                    nodes.Z_CY_B_07_055_MetalPaintedWhite_VRayMtl.geometry
                }
                material={materials["MetalPaintedWhite_VRayMtl.001"]}
                position={[8.988, 5.288, -7.974]}
                rotation={[0, 1.548, 0]}
                scale={3.935}
            />
            <mesh
                geometry={nodes.Z_CY_B_07_055_Z_BannerB_Atlas_mtl.geometry}
                material={materials["Z_BannerB_Atlas_mtl.001"]}
                position={[8.96, 2.253, -14.095]}
                rotation={[0, 1.509, 0]}
                scale={6.056}
            />
            <mesh
                geometry={nodes.Z_CY_B_07_063.geometry}
                material={materials.AtlasHoloB_mtl}
                position={[-4.129, 9.116, -27.354]}
                rotation={[-Math.PI, 0.959, -Math.PI]}
                scale={8.809}
            />
            <mesh
                geometry={nodes.Cube008.geometry}
                material={materials.PaletteMaterial003}
                position={[-4.658, 1.705, -17.672]}
                rotation={[0, 0.052, 0]}
                scale={1.67}
            />
            <mesh
                geometry={nodes.Cube167.geometry}
                material={materials.PaletteMaterial004}
                position={[-4.23, 4.631, 7.561]}
                rotation={[-Math.PI, 0.222, -Math.PI]}
                scale={0.988}
            />
            <mesh
                geometry={nodes.Cube166.geometry}
                material={materials.MT_Metall}
                position={[-4.852, 3.649, 7.419]}
                rotation={[-Math.PI, 0.222, -Math.PI]}
                scale={6.741}
            />
            <mesh
                geometry={nodes.Cube014.geometry}
                material={materials.PaletteMaterial005}
                position={[8.98, 4.353, -7.102]}
                rotation={[0, 0.092, 0]}
            />
            <mesh
                geometry={nodes.Pattern2D_6491.geometry}
                material={materials.Cloth}
                position={[4.118, 1.291, 16.892]}
                rotation={[1.626, 0.004, -3.077]}
                scale={0.002}
            />
            <group
                position={[-4.465, 4.991, 0.52]}
                rotation={[-Math.PI / 2, 0, 1.93]}
                scale={[0.599, 0.401, 0.593]}
            >
                <mesh
                    geometry={nodes.Mesh014.geometry}
                    material={materials.PaletteMaterial006}
                />
                <mesh
                    geometry={nodes.Mesh014_1.geometry}
                    material={materials["M.001"]}
                />
            </group>
            <group
                position={[7.382, 1.276, -25.184]}
                rotation={[-Math.PI, -1.52, 2.888]}
                scale={0.086}
            >
                <mesh
                    geometry={nodes.Plane013_1.geometry}
                    material={materials["Material.106"]}
                />
                <mesh
                    geometry={nodes.Plane013_2.geometry}
                    material={materials["Material.105"]}
                />
                <mesh
                    geometry={nodes.Plane013_3.geometry}
                    material={materials["Material.001_SMR"]}
                />
                <mesh
                    geometry={nodes.Plane013_4.geometry}
                    material={materials["Material.107"]}
                />
            </group>
            <group
                position={[3.936, 3.43, 18.069]}
                rotation={[-0.653, -0.058, -0.042]}
                scale={[5.808, 1.402, 2.477]}
            >
                <mesh
                    geometry={nodes.TexturesCom_Aircos0032_S003.geometry}
                    material={materials.TexturesCom_Aircos0032_S}
                />
                <mesh
                    geometry={nodes.TexturesCom_Aircos0032_S003_1.geometry}
                    material={materials.TexturesCom_Aircos0032_S_SEETHROUGH}
                />
            </group>
            <group
                position={[-4.671, 1.202, -13.17]}
                rotation={[-Math.PI, 1.552, -Math.PI]}
                scale={1.074}
            >
                <mesh
                    geometry={nodes.KB3D_CBP_VendingMachine_D_Main001.geometry}
                    material={materials.KB3D_CBP_AtlasDGBannerA}
                />
                <mesh
                    geometry={
                        nodes.KB3D_CBP_VendingMachine_D_Main001_1.geometry
                    }
                    material={materials.KB3D_CBP_SteelPanelShiny}
                />
                <mesh
                    geometry={
                        nodes.KB3D_CBP_VendingMachine_D_Main001_2.geometry
                    }
                    material={materials.Metal12}
                />
                <mesh
                    geometry={
                        nodes.KB3D_CBP_VendingMachine_D_Main001_3.geometry
                    }
                    material={materials.KB3D_CBP_SteelPanelBright}
                />
            </group>
            <mesh
                geometry={nodes.Cube004.geometry}
                material={materials.PaletteMaterial007}
                position={[8.143, 1.71, -8.691]}
                rotation={[Math.PI, -1.526, Math.PI]}
                scale={0.704}
            />
            <mesh
                geometry={nodes.Cube005.geometry}
                material={materials.PaletteMaterial008}
                position={[7.886, 2.732, -9.526]}
                rotation={[Math.PI, -1.526, Math.PI]}
                scale={0.007}
            />
            <group
                position={[8.013, 1.727, -8.811]}
                rotation={[Math.PI, -1.526, Math.PI]}
                scale={1.038}
            >
                <mesh
                    geometry={nodes.Cube008_1.geometry}
                    material={materials["vending material.001"]}
                />
                <mesh
                    geometry={nodes.Cube008_2.geometry}
                    material={materials["Emissive.001"]}
                />
                <mesh
                    geometry={nodes.Cube008_3.geometry}
                    material={materials["glowing vending.001"]}
                />
            </group>
            <group
                position={[-0.949, 1.543, 16.278]}
                rotation={[0, -0.089, 0]}
                scale={[0.692, 1.274, 0.539]}
            >
                <mesh
                    geometry={nodes.Cube009.geometry}
                    material={materials["Sioda Machine"]}
                />
                <mesh
                    geometry={nodes.Cube009_1.geometry}
                    material={materials["Glowing Bits"]}
                />
                <mesh
                    geometry={nodes.Cube009_2.geometry}
                    material={materials.rotten}
                />
            </group>
            <mesh
                geometry={nodes.Plane023.geometry}
                material={materials.Streetsign}
                position={[4.021, 4.471, -1.496]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={0.149}
            />
            <group
                position={[7.923, 0.052, -15.054]}
                rotation={[1.581, 0.259, -1.609]}
            >
                <mesh
                    geometry={nodes["20191109_145045001"].geometry}
                    material={materials["20191109_145045"]}
                />
                <mesh
                    geometry={nodes["20191109_145045001_1"].geometry}
                    material={materials["Rusty Box 1"]}
                />
            </group>
            <mesh
                geometry={nodes.Black_Air_Conditioner.geometry}
                material={materials["Black Air Conditioner"]}
                position={[8.739, 6.225, -17.408]}
                rotation={[0, -1.461, 0]}
                scale={[0.244, 0.178, 0.244]}
            />
            <mesh
                geometry={nodes.Electric_Box_Small.geometry}
                material={materials["Electric Box Small"]}
                position={[8.962, 6.877, -9.345]}
                rotation={[-3.133, 1.447, 0]}
                scale={-0.304}
            />
            <mesh
                geometry={nodes.Garbage_Container_Green.geometry}
                material={materials["Garbage Containers"]}
                position={[7.978, 0.385, -6.6]}
                rotation={[0, 1.317, 0]}
                scale={[0.512, 0.426, 0.426]}
            />
            <mesh
                geometry={nodes.Plane.geometry}
                material={materials["Material.015"]}
                position={[1.318, 0, -0.764]}
            />
            <mesh
                geometry={nodes.Cube016.geometry}
                material={materials["Material.003"]}
                position={[0.557, 8.248, -9.083]}
                scale={0.404}
            />
            <mesh
                geometry={nodes["high-polyMesh001"].geometry}
                material={materials["high-poly"]}
                position={[1.141, 0, 0]}
                rotation={[0, -1.571, 0]}
                scale={0.1}
            />
            <mesh
                geometry={nodes.short04Mesh001.geometry}
                material={materials.short04}
                position={[1.141, 0, 0]}
                rotation={[0, -1.571, 0]}
                scale={0.1}
            />
            <instancedMesh
                args={[nodes.Plane002.geometry, materials["Material.003"], 124]}
                instanceMatrix={nodes.Plane002.instanceMatrix}
            />
            <instancedMesh
                args={[
                    nodes.Cylinder003.geometry,
                    materials["aluminum.002"],
                    96,
                ]}
                instanceMatrix={nodes.Cylinder003.instanceMatrix}
            />
            <instancedMesh
                args={[
                    nodes.Cylinder003_1.geometry,
                    materials.PaletteMaterial001,
                    96,
                ]}
                instanceMatrix={nodes.Cylinder003_1.instanceMatrix}
            />
            <instancedMesh
                args={[
                    nodes.Cylinder003_2.geometry,
                    materials.PaletteMaterial007,
                    96,
                ]}
                instanceMatrix={nodes.Cylinder003_2.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Circle.geometry, materials["Material.023"], 5]}
                instanceMatrix={nodes.Circle.instanceMatrix}
            />
            <instancedMesh
                args={[nodes.Circle_1.geometry, materials["Material.024"], 5]}
                instanceMatrix={nodes.Circle_1.instanceMatrix}
            />
            <instancedMesh
                args={[
                    nodes.Circle_2.geometry,
                    materials.PaletteMaterial003,
                    5,
                ]}
                instanceMatrix={nodes.Circle_2.instanceMatrix}
            />
        </group>
    );
}

useGLTF.preload("/models//cyberCity-transformed.glb");
